// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package discount

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DiscountRuleEngineClient is the client API for DiscountRuleEngine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DiscountRuleEngineClient interface {
	CalculateDiscount(ctx context.Context, in *DiscountRequest, opts ...grpc.CallOption) (*DiscountReply, error)
}

type discountRuleEngineClient struct {
	cc grpc.ClientConnInterface
}

func NewDiscountRuleEngineClient(cc grpc.ClientConnInterface) DiscountRuleEngineClient {
	return &discountRuleEngineClient{cc}
}

func (c *discountRuleEngineClient) CalculateDiscount(ctx context.Context, in *DiscountRequest, opts ...grpc.CallOption) (*DiscountReply, error) {
	out := new(DiscountReply)
	err := c.cc.Invoke(ctx, "/discount.DiscountRuleEngine/CalculateDiscount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DiscountRuleEngineServer is the server API for DiscountRuleEngine service.
// All implementations must embed UnimplementedDiscountRuleEngineServer
// for forward compatibility
type DiscountRuleEngineServer interface {
	CalculateDiscount(context.Context, *DiscountRequest) (*DiscountReply, error)
	mustEmbedUnimplementedDiscountRuleEngineServer()
}

// UnimplementedDiscountRuleEngineServer must be embedded to have forward compatible implementations.
type UnimplementedDiscountRuleEngineServer struct {
}

func (UnimplementedDiscountRuleEngineServer) CalculateDiscount(context.Context, *DiscountRequest) (*DiscountReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CalculateDiscount not implemented")
}
func (UnimplementedDiscountRuleEngineServer) mustEmbedUnimplementedDiscountRuleEngineServer() {}

// UnsafeDiscountRuleEngineServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DiscountRuleEngineServer will
// result in compilation errors.
type UnsafeDiscountRuleEngineServer interface {
	mustEmbedUnimplementedDiscountRuleEngineServer()
}

func RegisterDiscountRuleEngineServer(s grpc.ServiceRegistrar, srv DiscountRuleEngineServer) {
	s.RegisterService(&DiscountRuleEngine_ServiceDesc, srv)
}

func _DiscountRuleEngine_CalculateDiscount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiscountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscountRuleEngineServer).CalculateDiscount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/discount.DiscountRuleEngine/CalculateDiscount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscountRuleEngineServer).CalculateDiscount(ctx, req.(*DiscountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DiscountRuleEngine_ServiceDesc is the grpc.ServiceDesc for DiscountRuleEngine service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DiscountRuleEngine_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "discount.DiscountRuleEngine",
	HandlerType: (*DiscountRuleEngineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CalculateDiscount",
			Handler:    _DiscountRuleEngine_CalculateDiscount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/discount.proto",
}
